# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_sortDelta <- function(x) {
    .Call(`_SamplingStrataC_Rcpp_sortDelta`, x)
}

aggrStrata_RcppOpen <- function(strata, nvar, vett, censiti, dominio) {
    .Call(`_SamplingStrataC_aggrStrata_RcppOpen`, strata, nvar, vett, censiti, dominio)
}

uppercasevec <- function(df) {
    .Call(`_SamplingStrataC_uppercasevec`, df)
}

grepRcpp <- function(pattern, x) {
    .Call(`_SamplingStrataC_grepRcpp`, pattern, x)
}

seqRcpp <- function(vx) {
    .Call(`_SamplingStrataC_seqRcpp`, vx)
}

int_to_string <- function(addr) {
    .Call(`_SamplingStrataC_int_to_string`, addr)
}

paste3 <- function(lhs, rhs) {
    .Call(`_SamplingStrataC_paste3`, lhs, rhs)
}

repRcpp <- function(x, times) {
    .Call(`_SamplingStrataC_repRcpp`, x, times)
}

repRcpp2 <- function(x, n) {
    .Call(`_SamplingStrataC_repRcpp2`, x, n)
}

repRcppdouble <- function(x, n) {
    .Call(`_SamplingStrataC_repRcppdouble`, x, n)
}

testDFtoNM1 <- function(x) {
    .Call(`_SamplingStrataC_testDFtoNM1`, x)
}

ordina_variabiliRcpp <- function(dati, prefisso, n_var) {
    .Call(`_SamplingStrataC_ordina_variabiliRcpp`, dati, prefisso, n_var)
}

ndomRcpp <- function(prefisso, n_vars) {
    .Call(`_SamplingStrataC_ndomRcpp`, prefisso, n_vars)
}

nvaluesRcpp <- function(nom_dom, dom) {
    .Call(`_SamplingStrataC_nvaluesRcpp`, nom_dom, dom)
}

crea_disjRcpp <- function(data, pref) {
    .Call(`_SamplingStrataC_crea_disjRcpp`, data, pref)
}

dfrow <- function(x, num) {
    .Call(`_SamplingStrataC_dfrow`, x, num)
}

int_to_charvec <- function(addr) {
    .Call(`_SamplingStrataC_int_to_charvec`, addr)
}

paste4 <- function(lhs, rhs) {
    .Call(`_SamplingStrataC_paste4`, lhs, rhs)
}

testDFtoNM3 <- function(x) {
    .Call(`_SamplingStrataC_testDFtoNM3`, x)
}

ordina_variabiliRcpp2 <- function(dati, prefisso, n_var) {
    .Call(`_SamplingStrataC_ordina_variabiliRcpp2`, dati, prefisso, n_var)
}

cbindRcpp <- function(a, b) {
    .Call(`_SamplingStrataC_cbindRcpp`, a, b)
}

cbindRcpp1 <- function(a, b) {
    .Call(`_SamplingStrataC_cbindRcpp1`, a, b)
}

vecconcat <- function(x, y) {
    .Call(`_SamplingStrataC_vecconcat`, x, y)
}

stringrepRcpp <- function(x, y) {
    .Call(`_SamplingStrataC_stringrepRcpp`, x, y)
}

concat <- function(x, y) {
    .Call(`_SamplingStrataC_concat`, x, y)
}

stringrepRcpp2 <- function(x, y) {
    .Call(`_SamplingStrataC_stringrepRcpp2`, x, y)
}

crea_aRcpp <- function(N11, s11, nocens11, m11, cv11, epsilon = 1e-11) {
    .Call(`_SamplingStrataC_crea_aRcpp`, N11, s11, nocens11, m11, cv11, epsilon)
}

a13 <- function(x) {
    .Call(`_SamplingStrataC_a13`, x)
}

chromyNew1 <- function(alfatot, diff, iter, alfa, alfanext, x, a, cost, epsilon = 1e-11, maxiter = 200L, realAllocation = TRUE) {
    .Call(`_SamplingStrataC_chromyNew1`, alfatot, diff, iter, alfa, alfanext, x, a, cost, epsilon, maxiter, realAllocation)
}

bethelRcppOpen <- function(stratif, errors, minnumstrat = 2L, maxiter = 200L, maxiter1 = 5L, printa = TRUE, realAllocation = TRUE, epsilon = 1e-11) {
    .Call(`_SamplingStrataC_bethelRcppOpen`, stratif, errors, minnumstrat, maxiter, maxiter1, printa, realAllocation, epsilon)
}

stdev_Rcpp <- function(dataset, i, fitting, range, kappa) {
    .Call(`_SamplingStrataC_stdev_Rcpp`, dataset, i, fitting, range, kappa)
}

