# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_sortDelta <- function(x) {
    .Call(`_SamplingStrata_Rcpp_sortDelta`, x)
}

aggrStrata_RcppOpen <- function(strata, nvar, vett, censiti, dominio) {
    .Call(`_SamplingStrata_aggrStrata_RcppOpen`, strata, nvar, vett, censiti, dominio)
}

select_variables <- function(dati, prefix, nvar) {
    .Call(`_SamplingStrata_select_variables`, dati, prefix, nvar)
}

disjoint <- function(dom) {
    .Call(`_SamplingStrata_disjoint`, dom)
}

m_s <- function(disj, mat) {
    .Call(`_SamplingStrata_m_s`, disj, mat)
}

rowSums_Rcpp <- function(x) {
    .Call(`_SamplingStrata_rowSums_Rcpp`, x)
}

colSums_Rcpp <- function(x) {
    .Call(`_SamplingStrata_colSums_Rcpp`, x)
}

cv_Rcpp <- function(errors, ndom, nvar) {
    .Call(`_SamplingStrata_cv_Rcpp`, errors, ndom, nvar)
}

crea_a <- function(m, s, nocens, N, cv, epsilon) {
    .Call(`_SamplingStrata_crea_a`, m, s, nocens, N, cv, epsilon)
}

chromy_Rcpp <- function(a, alfatot, diff, iter, alfa, alfanext, x, cost, nvar, realAllocation) {
    .Call(`_SamplingStrata_chromy_Rcpp`, a, alfatot, diff, iter, alfa, alfanext, x, cost, nvar, realAllocation)
}

check_n <- function(n, N, minnumstrat) {
    .Call(`_SamplingStrata_check_n`, n, N, minnumstrat)
}

bethel_Rcpp <- function(strata, errors, minnumstrat, realAllocation = 1L) {
    .Call(`_SamplingStrata_bethel_Rcpp`, strata, errors, minnumstrat, realAllocation)
}

stdev_Rcpp <- function(dataset, i, fitting, range, kappa) {
    .Call(`_SamplingStrata_stdev_Rcpp`, dataset, i, fitting, range, kappa)
}

